const API='https://dbxvfrkkocfwjumvoaha.supabase.co/functions/v1/field-monitoring-dashboard';
const app=document.getElementById('app');let hours=24;
const names={LOCATION_MISMATCH:'عدم تطابق الموقع',SHARED_DEVICE_MULTIPLE_IDENTITIES:'جهاز مشترك بين هويات متعددة',CHECKPOINT_IMPOSSIBLE_MOVE:'حركة غير ممكنة زمنياً',FAST_REPEAT:'تكرار سريع',LOW_ACCURACY:'دقة موقع منخفضة',IDENTITY_MULTIPLE_DEVICES:'هوية تظهر من عدة أجهزة',RAPID_MULTI_QR_SAME_DEVICE:'مسح عدة رموز سريعاً',NO_LOCATION:'لا يوجد موقع صالح'};
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function n(v){return Number(v||0).toLocaleString('ar-SA')}function pct(v){return v==null?'—':Number(v).toFixed(1)+'%'}
function dt(v){if(!v)return'—';try{return new Intl.DateTimeFormat('ar-SA',{timeZone:'Asia/Riyadh',dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch(_){return String(v)}}
function accessKey(){let k='';try{k=sessionStorage.getItem('ark_field_monitor_key')||''}catch(_){}const h=new URLSearchParams((location.hash||'').replace(/^#/,'')),x=h.get('k')||'';if(x){k=x;try{sessionStorage.setItem('ark_field_monitor_key',k)}catch(_){}history.replaceState(null,'',location.pathname)}return k}
function kpi(t,v,d){return '<div class="kpi"><small>'+esc(t)+'</small><strong>'+esc(v)+'</strong><span>'+esc(d||'')+'</span></div>'}
function issue(x){return '<article class="issue clickable" data-cp="'+esc(x.checkpoint_code||'')+'"><div><span class="tag '+esc(x.severity)+'">'+(x.severity==='high'?'أولوية مراجعة':'مراجعة')+'</span><h4>'+esc(names[x.flag]||x.flag)+'</h4><p>QR: '+esc(x.checkpoint_code||'—')+' · أشخاص '+n(x.guards)+' · أجهزة '+n(x.devices)+' · آخر ظهور '+esc(dt(x.last_seen_at))+'</p><button class="detail-btn" type="button">عرض التفاصيل</button></div><div class="num"><strong>'+n(x.events)+'</strong><small>إشارة</small></div></article>'}
function bars(a){a=(a||[]).slice(0,8);const m=Math.max(1,...a.map(x=>+x.events||0));return a.map(x=>'<div class="bar-row"><label>'+esc(names[x.flag]||x.flag)+'</label><div class="bar"><i style="width:'+Math.max(2,Math.round(100*(+x.events||0)/m))+'%"></i></div><b>'+n(x.events)+'</b></div>').join('')||'<div class="sub">لا توجد إشارات.</div>'}
function trend(a){a=a||[];const m=Math.max(1,...a.map(x=>+x.scans||0));return '<div class="trend">'+a.map(x=>'<i title="'+esc(dt(x.bucket))+' · '+n(x.scans)+'" style="height:'+Math.max(3,Math.round(100*(+x.scans||0)/m))+'%"></i>').join('')+'</div>'}
function render(x){const s=x.summary||{},v=x.virtual_points||{},st=x.storage||{},w=x.workflow||{},r=x.review_queue||[],id=x.identity_review||[],ph=x.photo_device_review||[],high=r.filter(z=>z.severity==='high').length;
app.innerHTML='<section class="kpis">'+
kpi('المسحات',n(s.total_scans),'خلال '+x.window_hours+' ساعة')+kpi('الحراس المطابقون',n(s.unique_guards),'هويات موظفين فريدة')+kpi('نقاط QR النشطة',n(s.unique_checkpoints),'ظهرت خلال الفترة')+kpi('الأدلة المكتملة',pct(s.complete_evidence_rate),'هوية + موقع جيد + صورة')+
kpi('اكتمال الصور',pct(s.photo_rate),n(s.photo_ok)+' صورة مرتبطة')+kpi('جودة الموقع',pct(s.good_location_rate),'GPS بدقة 100م أو أفضل')+kpi('مطابقة الهوية',pct(s.identity_rate),n(s.identity_ok)+' مسحة مطابقة')+kpi('إشارات عالية للمراجعة',n(high),'مجمعة على مستوى QR')+'</section>'+
'<div class="grid2"><section class="panel"><div class="panel-head"><div><h3>قائمة المراجعة بالأولوية</h3><div class="sub">تجميع حسب QR لمنع تضخم التنبيهات.</div></div><span class="tag">'+n(r.length)+' مجموعة</span></div><div class="queue">'+(r.length?r.slice(0,14).map(issue).join(''):'<div class="sub">لا توجد حالات.</div>')+'</div></section><section class="panel"><h3>توزيع إشارات المراجعة</h3><div class="sub">لا تُقرأ كحالات مخالفة مؤكدة.</div>'+bars(x.anomalies)+'</section></div>'+
'<div class="grid2"><section class="panel"><h3>حركة الرصد</h3><div class="sub">بتوقيت السعودية.</div>'+trend(x.trend)+'</section><section class="panel"><h3>نضج نقاط الرصد</h3><div class="kpis" style="grid-template-columns:repeat(3,1fr);margin-top:10px">'+kpi('مثبتة',n(v.established),'Established')+kpi('مؤقتة',n(v.provisional),'Provisional')+kpi('الإجمالي',n(v.total),'نقاط افتراضية')+'</div><div class="sub" style="margin-top:12px">تخزين أدلة الرصد: '+Number(st.gb||0).toFixed(3)+' GB · '+n(st.objects)+' ملف.</div></section></div>'+
'<div class="grid2"><section class="panel"><h3>مطابقة الهوية</h3><table class="table"><thead><tr><th>الحالة</th><th>المسحات</th><th>النقاط</th></tr></thead><tbody>'+(id.length?id.map(z=>'<tr><td>'+esc(z.match_status)+'</td><td class="num">'+n(z.events)+'</td><td class="num">'+n(z.checkpoints)+'</td></tr>').join(''):'<tr><td colspan="3">لا توجد حالات.</td></tr>')+'</tbody></table></section><section class="panel"><h3>أجهزة تحتاج مراجعة دليل الصورة</h3><table class="table"><thead><tr><th>الموظف / الجهاز</th><th>مفقود</th><th>النسبة</th></tr></thead><tbody>'+(ph.length?ph.slice(0,10).map(z=>'<tr><td>'+esc(z.full_name||z.device_ref||'غير مطابق')+'</td><td class="num">'+n(z.missing_photos)+'</td><td class="num">'+pct(z.photo_rate)+'</td></tr>').join(''):'<tr><td colspan="3">لا توجد حالات.</td></tr>')+'</tbody></table></section></div>'+
'<section class="panel" style="margin-top:14px"><h3>توزيع نوع العملية</h3><div class="kpis" style="grid-template-columns:repeat(3,1fr);margin-top:10px">'+kpi('بدء الوردية',n(w.start_shift),'Start Shift')+kpi('إثبات التحضير',n(w.field_check),'Field Check')+kpi('انتهاء الوردية',n(w.end_shift),'End Shift')+'</div></section><div class="stamp">آخر تحديث: '+esc(dt(x.generated_at))+'</div>'}
async function load(){const k=accessKey();if(!k){app.innerHTML='<div class="state bad">رابط لوحة الرصد غير مكتمل أو انتهت جلسة الوصول.</div>';return}app.innerHTML='<div class="state"><div class="spin"></div>جارٍ تحديث مؤشرات الرصد…</div>';try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key:k,hours}),cache:'no-store'}),x=await r.json();if(!r.ok||!x.ok)throw new Error(x.message||'تعذر تحميل البيانات');render(x)}catch(e){app.innerHTML='<div class="state bad">'+esc(e.message||'تعذر تحميل لوحة الرصد.')+'</div>'}}
document.getElementById('controls').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.h){hours=+b.dataset.h;document.querySelectorAll('[data-h]').forEach(x=>x.classList.toggle('active',x===b));load()}else if(b.id==='refresh')load()});load();
function scanFlags(a){return (a||[]).map(x=>names[x]||x).join('، ')||'—'}
function closeDetail(){const m=document.getElementById('detailModal');if(m)m.remove()}
function detailTable(rows){return '<div class="detail-scroll"><table class="table"><thead><tr><th>الوقت</th><th>الموظف</th><th>العملية</th><th>التكليف</th><th>GPS</th><th>صورة</th><th>الإشارات</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+esc(dt(r.server_ts))+'</td><td>'+esc(r.full_name||r.employee_id||'غير مطابق')+'</td><td>'+esc(r.attendance_action||'—')+'</td><td>'+esc(r.assignment_class||'—')+'</td><td>'+esc(r.accuracy_m==null?'—':Math.round(Number(r.accuracy_m))+'م')+(r.maps_url?' <a href="'+esc(r.maps_url)+'" target="_blank" rel="noopener">خريطة</a>':'')+'</td><td>'+esc(r.photo_present?'موجودة':'مفقودة')+'</td><td>'+esc(scanFlags(r.review_flags))+'</td></tr>').join('')+'</tbody></table></div>'}
async function openDetail(cp){
  const k=accessKey();if(!cp||!k)return;
  closeDetail();
  document.body.insertAdjacentHTML('beforeend','<div class="modal-backdrop" id="detailModal"><section class="modal"><div class="modal-head"><div><h3>تفاصيل '+esc(cp)+'</h3><div class="sub">تحليل جميع المسحات المرتبطة بالنقطة ضمن الفترة المحددة.</div></div><button type="button" id="closeDetail">إغلاق</button></div><div id="detailBody" class="state"><div class="spin"></div>جارٍ تحميل التفاصيل…</div></section></div>');
  document.getElementById('closeDetail').onclick=closeDetail;
  document.getElementById('detailModal').addEventListener('click',e=>{if(e.target.id==='detailModal')closeDetail()});
  try{
    const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key:k,hours,action:'checkpoint_detail',checkpoint_code:cp}),cache:'no-store'}),x=await r.json();
    if(!r.ok||!x.ok)throw new Error(x.message||'تعذر تحميل التفاصيل');
    const s=x.summary||{},people=x.people||[],rows=x.scans||[];
    document.getElementById('detailBody').className='';
    document.getElementById('detailBody').innerHTML='<div class="detail-kpis">'+kpi('المسحات',n(s.total_scans),'')+kpi('الحراس',n(s.guards),'')+kpi('الأجهزة',n(s.devices),'')+kpi('اكتمال الصور',pct(s.photo_rate),'')+kpi('مطابقة الهوية',pct(s.identity_rate),'')+kpi('جودة الموقع',pct(s.good_location_rate),'')+'</div><h4 class="detail-title">أكثر الأشخاص ظهوراً</h4><div class="people-grid">'+people.slice(0,12).map(p=>'<div class="person-card"><b>'+esc(p.full_name||p.employee_id||'غير مطابق')+'</b><span>'+n(p.scans)+' مسحات · '+pct(p.photo_rate)+' صور · '+n(p.devices)+' جهاز</span></div>').join('')+'</div><h4 class="detail-title">آخر المسحات</h4>'+detailTable(rows.slice(0,100));
  }catch(e){document.getElementById('detailBody').innerHTML='<div class="state bad">'+esc(e.message||'تعذر تحميل التفاصيل.')+'</div>'}
}
document.addEventListener('click',e=>{const b=e.target.closest('.detail-btn');if(!b)return;const card=b.closest('[data-cp]');if(card)openDetail(card.getAttribute('data-cp'))});
