const API='https://dbxvfrkkocfwjumvoaha.supabase.co/functions/v1/field-project-dashboard';
const app=document.getElementById('app'),projectSelect=document.getElementById('projectSelect');
let hours=24,projectId='',aborter=null;const cache=new Map();
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function n(v){return Number(v||0).toLocaleString('ar-SA')}function pct(v){return v==null?'—':Number(v).toFixed(1)+'%'}
function dt(v){if(!v)return'—';try{return new Intl.DateTimeFormat('ar-SA',{timeZone:'Asia/Riyadh',dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch(_){return String(v)}}
function accessKey(){let k='';try{k=sessionStorage.getItem('ark_field_monitor_key')||''}catch(_){}const h=new URLSearchParams((location.hash||'').replace(/^#/,'')),x=h.get('k')||'';if(x){k=x;try{sessionStorage.setItem('ark_field_monitor_key',k)}catch(_){}history.replaceState(null,'',location.pathname)}return k}
function kpi(t,v,d,cls=''){return '<div class="kpi '+cls+'"><small>'+esc(t)+'</small><strong>'+esc(v)+'</strong><span>'+esc(d||'')+'</span></div>'}
function qualityClass(v){v=Number(v||0);return v>=95?'good':v>=85?'warn-txt':'bad-txt'}
function trend(a){a=a||[];const m=Math.max(1,...a.map(x=>+x.scans||0));return '<div class="trend">'+a.map(x=>'<i title="'+esc(dt(x.bucket))+' · '+n(x.scans)+'" style="height:'+Math.max(4,Math.round((+x.scans||0)*100/m))+'%"></i>').join('')+'</div>'}
function renderProjects(list){projectSelect.innerHTML=(list||[]).map(p=>'<option value="'+esc(p.project_id)+'">'+esc(p.client_name)+' — '+esc(p.project_name)+'</option>').join('');if(!projectId&&list&&list.length)projectId=list[0].project_id;projectSelect.value=projectId}
function render(x){const p=x.project||{},s=x.summary||{},sh=x.shift||{},ex=x.exceptions||{},gps=x.guard_points||[],sup=x.supervisors||[];renderProjects(x.projects||[p]);
const pointsRows=gps.map(g=>'<tr class="clickable" data-cp="'+esc(g.checkpoint_code)+'"><td><b>'+esc(g.checkpoint_code)+'</b></td><td class="num">'+n(g.scans)+'</td><td class="num">'+n(g.guards)+'</td><td class="num '+qualityClass(g.photo_rate)+'">'+pct(g.photo_rate)+'</td><td class="num '+qualityClass(g.good_location_rate)+'">'+pct(g.good_location_rate)+'</td><td class="num '+(g.unmatched_scans?'warn-txt':'good')+'">'+n(g.unmatched_scans)+'</td><td>'+esc(dt(g.last_seen_at))+'</td></tr>').join('');
const supRows=sup.map(z=>'<tr><td>'+esc(z.supervisor_name||'غير مطابق')+'</td><td>'+esc(z.supervisor_employee_id||'—')+'</td><td class="num">'+n(z.checkpoints)+'</td><td class="num">'+n(z.scans)+'</td><td>'+esc(dt(z.last_seen_at))+'</td></tr>').join('');
app.innerHTML='<section class="project-head"><div><h2>'+esc(p.client_name)+'</h2><p>'+esc(p.project_name)+' · '+esc(p.site_name||p.site_id||'')+' · '+esc(p.project_id)+'</p></div><span class="tag">Pilot سريع</span></section>'+
'<section class="kpis">'+kpi('المسحات',n(s.scans),'خلال '+x.window_hours+' ساعة')+kpi('الحراس الظاهرون',n(s.guards),'منهم '+n(s.native_guards)+' تابعون للمشروع')+kpi('نقاط QR النشطة',n(s.qr_codes),'ضمن نطاق المشروع')+kpi('المشرفون النشطون',n(s.supervisors),'ظهروا في الرصد')+kpi('اكتمال الصور',pct(s.photo_rate),'دليل صورة',Number(s.photo_rate)<90?'warn':'')+kpi('جودة الموقع',pct(s.good_location_rate),'GPS ≤ 100م',Number(s.good_location_rate)<90?'warn':'')+kpi('مطابقة الهوية',pct(s.identity_rate),'من إجمالي المسحات',Number(s.identity_rate)<90?'warn':'')+kpi('خطة التغطية المعتمدة','غير محملة','لن نحسب Coverage % قبل Deployment Plan','neutral')+'</section>'+
'<div class="grid2"><section class="panel"><h3>الاستثناءات الحالية</h3><div class="sub">تعرض ما يحتاج مراجعة دون تحميل سجل المسحات الخام.</div><div class="exception-grid"><div class="exception"><b>'+n(ex.unmatched_scans)+'</b><span>مسحات بهوية غير مطابقة</span></div><div class="exception"><b>'+n(ex.cross_project_scans)+'</b><span>ظهور لموظفين تابعين لمشاريع أخرى</span></div><div class="exception"><b>'+n(ex.missing_photo)+'</b><span>مسحات بلا صورة</span></div><div class="exception"><b>'+n(ex.bad_or_missing_location)+'</b><span>GPS مفقود/ضعيف</span></div></div></section><section class="panel"><h3>حركة الرصد</h3><div class="sub">تجميع ساعي فقط — لا يتم تحميل الأحداث الفردية.</div>'+trend(x.trend)+'</section></div>'+
'<div class="grid2"><section class="panel"><h3>مدة الورديات — قراءة تجريبية</h3><div class="sub">تُحسب من Start → End؛ نقص End Shift يخفض معدل الاقتران ولا يُعامل كغياب تلقائياً.</div><div class="shift-box">'+kpi('Start',n(sh.starts),'')+kpi('أزواج مكتملة',n(sh.paired),'')+kpi('معدل الاقتران',pct(sh.pair_rate),'')+kpi('الوسيط',sh.median_hours==null?'—':Number(sh.median_hours).toFixed(2)+' س','')+'</div></section><section class="panel"><h3>توزيع العمليات</h3><div class="shift-box">'+kpi('بدء وردية',n(s.start_shift),'')+kpi('إثبات تحضير',n(s.field_check),'')+kpi('انتهاء وردية',n(s.end_shift),'')+kpi('آخر نشاط',dt(s.last_seen_at),'','neutral')+'</div></section></div>'+
'<div class="grid2"><section class="panel"><h3>نقاط الحراسة</h3><div class="sub">اضغط على أي QR لتحميل التفاصيل عند الطلب فقط.</div><div class="table-wrap"><table class="table"><thead><tr><th>QR</th><th>مسحات</th><th>حراس</th><th>صور</th><th>GPS</th><th>غير مطابق</th><th>من مشاريع أخرى</th><th>آخر ظهور</th></tr></thead><tbody>'+pointsRows+'</tbody></table></div></section><section class="panel"><h3>المشرفون</h3><div class="table-wrap"><table class="table"><thead><tr><th>المشرف</th><th>EMP_ID</th><th>نقاط</th><th>مسحات</th><th>آخر ظهور</th></tr></thead><tbody>'+supRows+'</tbody></table></div></section></div>'+
'<div class="stamp">آخر تحديث: '+esc(dt(x.generated_at))+' · البيانات الخام تُجلب فقط عند فتح تفاصيل نقطة.</div>'}
async function call(body,signal){const k=accessKey();if(!k)throw new Error('رابط الوصول غير مكتمل.');const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...body,key:k}),cache:'no-store',signal});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.message||'تعذر تحميل البيانات');return x}
async function load(force=false){if(aborter)aborter.abort();aborter=new AbortController();const ck=(projectId||'default')+'|'+hours,c=cache.get(ck);if(!force&&c&&Date.now()-c.t<20000){render(c.x);return}app.innerHTML='<div class="state"><div class="spin"></div>جارٍ تحميل مؤشرات المشروع…</div>';try{const x=await call({action:'summary',project_id:projectId||null,hours},aborter.signal);projectId=x.project.project_id;cache.set(projectId+'|'+hours,{t:Date.now(),x});render(x)}catch(e){if(e.name==='AbortError')return;app.innerHTML='<div class="state">'+esc(e.message||'تعذر تحميل البيانات')+'</div>'}}
function closeModal(){document.getElementById('modal')?.remove()}
async function detail(cp){closeModal();document.body.insertAdjacentHTML('beforeend','<div class="modal-bg" id="modal"><section class="modal"><div class="modal-head"><div><h3>'+esc(cp)+'</h3><div class="sub">تفاصيل تُحمّل عند الطلب فقط.</div></div><button id="modalClose">إغلاق</button></div><div class="modal-body" id="modalBody"><div class="state"><div class="spin"></div>جارٍ التحميل…</div></div></section></div>');document.getElementById('modalClose').onclick=closeModal;document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
try{const x=await call({action:'checkpoint_detail',project_id:projectId,checkpoint_code:cp,hours});const s=x.summary||{},people=x.people||[],geo=x.geography||[],rows=x.recent_scans||[];document.getElementById('modalBody').innerHTML='<div class="kpis">'+kpi('المسحات',n(s.scans),'')+kpi('الحراس',n(s.guards),'')+kpi('غير مطابق',n(s.unmatched_scans),'')+kpi('من مشاريع أخرى',n(s.cross_project_guards),'')+kpi('جودة الموقع',pct(s.good_location_rate),'')+'</div><h3 style="margin-top:16px">المواقع الفعلية</h3><div class="geo">'+(geo.length?geo.map(g=>'<span>'+esc(g.city_name||'')+' — '+esc(g.region_name||'')+' · '+esc(g.virtual_point_id)+'</span>').join(''):'<span>لا توجد نقطة افتراضية مكتملة بعد</span>')+'</div><h3 style="margin-top:16px">الأشخاص الأكثر ظهوراً</h3><div class="people">'+people.slice(0,18).map(p=>'<div class="person"><b>'+esc(p.person_label||p.employee_id||'غير مطابق')+'</b><span>'+n(p.scans)+' مسحات · صور '+pct(p.photo_rate)+' · GPS '+pct(p.good_location_rate)+(p.cross_project?' · مشروع آخر':'')+'</span></div>').join('')+'</div><h3 style="margin-top:16px">آخر المسحات</h3><div class="table-wrap"><table class="table"><thead><tr><th>الوقت</th><th>الموظف</th><th>العملية</th><th>GPS</th><th>صورة</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+esc(dt(r.server_ts))+'</td><td>'+esc(r.person_label||r.employee_id||'غير مطابق')+'</td><td>'+esc(r.attendance_action||'—')+'</td><td>'+esc(r.accuracy_m==null?'—':Math.round(Number(r.accuracy_m))+'م')+'</td><td>'+esc(r.photo_present?'نعم':'لا')+'</td></tr>').join('')+'</tbody></table></div>'}catch(e){document.getElementById('modalBody').innerHTML='<div class="state">'+esc(e.message||'تعذر تحميل التفاصيل')+'</div>'}}
document.querySelector('.toolbar').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.h){hours=+b.dataset.h;document.querySelectorAll('[data-h]').forEach(x=>x.classList.toggle('active',x===b));load()}else if(b.id==='refresh')load(true)});
projectSelect.addEventListener('change',()=>{projectId=projectSelect.value;load(true)});
document.addEventListener('click',e=>{const tr=e.target.closest('tr[data-cp]');if(tr)detail(tr.dataset.cp)});
load();